//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimberV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.DraftCarts = new HashSet<DraftCart>();
            this.Orders = new HashSet<Order>();
            this.Reviews = new HashSet<Review>();
        }

        public int UserID { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string UserEmail { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage = "Maximum 20 charecters allowed")]
        [MinLength(6, ErrorMessage = "Minimum 6 charecters needed")]
        public string UserPass { get; set; }
        [Required]
        [Compare("UserPass", ErrorMessage = "Password And Confirm Password Mismatch")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirm PassWord")]
        public string ConfirmUserPassword { get; set; }
        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Name")]
        //[Range(6,20,ErrorMessage ="User Name Must Be Between 6 and 20 charecters")]
        public string UserName { get; set; }
        [Required]
        [Display(Name = "Address")]
        public string UserAddress { get; set; }
        public int IsAdmin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DraftCart> DraftCarts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
